python trainNvidiaDrop.py --dataPath ./Record,./Recovery --epochs 5 --offset 0.25 --output nvidDrp0_25 %*
python trainNvidiaDrop.py --dataPath ./Record,./Recovery --epochs 5 --offset 0.2 --output nvidDrp0_2 %*
python trainNvidiaDrop.py --dataPath ./Record,./Recovery --epochs 5 --offset 0.15 --output nvidDrp0_15 %*
python trainNvidiaDrop.py --dataPath ./Record,./Recovery --epochs 5 --offset 0.1 --output nvidDrp0_1 %*
python trainNvidia.py --dataPath ./Record,./Recovery --epochs 5 --offset 0.25 --output nvid0_25 %*
python trainNvidia.py --dataPath ./Record,./Recovery --epochs 5 --offset 0.2 --output nvid0_2 %*
python trainNvidia.py --dataPath ./Record,./Recovery --epochs 5 --offset 0.15 --output nvid0_15 %*
python trainNvidia.py --dataPath ./Record,./Recovery --epochs 5 --offset 0.1 --output nvid0_1 %*
python trainTheModel.py --dataPath ./Record,./Recovery --epochs 5 --offset 0.25 --output LaNet0_25 %*
python trainTheModel.py --dataPath ./Record,./Recovery --epochs 5 --offset 0.2 --output LaNet0_2 %*
python trainTheModel.py --dataPath ./Record,./Recovery --epochs 5 --offset 0.15 --output LaNet0_15 %*
python trainTheModel.py --dataPath ./Record,./Recovery --epochs 5 --offset 0.1 --output LaNet0_1 %*
python trainNvidia.py --dataPath ./Record,./Recovery,./RecordOpposite --epochs 5 --offset 0.25 --output nvidOp0_25 %*
python trainNvidia.py --dataPath ./Record,./Recovery,./RecordOpposite --epochs 5 --offset 0.2 --output nvidOp0_2 %*
python trainNvidia.py --dataPath ./Record,./Recovery,./RecordOpposite --epochs 5 --offset 0.15 --output nvidOp0_15 %*
python trainNvidia.py --dataPath ./Record,./Recovery,./RecordOpposite --epochs 5 --offset 0.1 --output nvidOp0_1 %*
python trainNvidia.py --dataPath ./Record1,./Record1Opposite --epochs 5 --offset 0.25 --output nvid1Op0_25 %*
python trainNvidia.py --dataPath ./Record1,./Record1Opposite --epochs 5 --offset 0.2 --output nvid1Op0_2 %*
python trainNvidia.py --dataPath ./Record1,./Record1Opposite --epochs 5 --offset 0.15 --output nvid1Op0_15 %*
python trainNvidia.py --dataPath ./Record1,./Record1Opposite --epochs 5 --offset 0.1 --output nvid1Op0_1 %*
python trainNvidia.py --dataPath ./Record1 --epochs 5 --offset 0.25 --output nvid10_25 %*
python trainNvidia.py --dataPath ./Record1 --epochs 5 --offset 0.2 --output nvid10_2 %*
python trainNvidia.py --dataPath ./Record1 --epochs 5 --offset 0.15 --output nvid10_15 %*
python trainNvidia.py --dataPath ./Record1 --epochs 5 --offset 0.1 --output nvid10_1 %*
python trainNvidia.py --dataPath ./Record,./Recovery,./RecordOpposite,./Record1,./Record1Opposite --epochs 5 --offset 0.25 --output nvidAll0_25 %*
python trainNvidia.py --dataPath ./Record,./Recovery,./RecordOpposite,./Record1,./Record1Opposite --epochs 5 --offset 0.2 --output nvidAll0_2 %*
python trainNvidia.py --dataPath ./Record,./Recovery,./RecordOpposite,./Record1,./Record1Opposite --epochs 5 --offset 0.15 --output nvidAll0_15 %*
python trainNvidia.py --dataPath ./Record,./Recovery,./RecordOpposite,./Record1,./Record1Opposite --epochs 5 --offset 0.1 --output nvidAll0_1 %*
python trainNvidiaDrop.py --dataPath ./Record,./Recovery,./RecordOpposite --epochs 5 --offset 0.25 --output nvidOpDrp0_25 %*
python trainNvidiaDrop.py --dataPath ./Record,./Recovery,./RecordOpposite --epochs 5 --offset 0.2 --output nvidOpDrp0_2 %*
python trainNvidiaDrop.py --dataPath ./Record,./Recovery,./RecordOpposite --epochs 5 --offset 0.15 --output nvidOpDrp0_15 %*
python trainNvidiaDrop.py --dataPath ./Record,./Recovery,./RecordOpposite --epochs 5 --offset 0.1 --output nvidOpDrp0_1 %*
python trainNvidiaDrop.py --dataPath ./Record1,./Record1Opposite --epochs 5 --offset 0.25 --output nvid1OpDrp0_25 %*
python trainNvidiaDrop.py --dataPath ./Record1,./Record1Opposite --epochs 5 --offset 0.2 --output nvid1OpDrp0_2 %*
python trainNvidiaDrop.py --dataPath ./Record1,./Record1Opposite --epochs 5 --offset 0.15 --output nvid1OpDrp0_15 %*
python trainNvidiaDrop.py --dataPath ./Record1,./Record1Opposite --epochs 5 --offset 0.1 --output nvid1OpDrp0_1 %*
python trainNvidiaDrop.py --dataPath ./Record1 --epochs 5 --offset 0.25 --output nvid1Drp0_25 %*
python trainNvidiaDrop.py --dataPath ./Record1 --epochs 5 --offset 0.2 --output nvid1Drp0_2 %*
python trainNvidiaDrop.py --dataPath ./Record1 --epochs 5 --offset 0.15 --output nvid1Drp0_15 %*
python trainNvidiaDrop.py --dataPath ./Record1 --epochs 5 --offset 0.1 --output nvid1Drp0_1 %*
python trainNvidiaDrop.py --dataPath ./Record,./Recovery,./RecordOpposite,./Record1,./Record1Opposite --epochs 5 --offset 0.25 --output nvidAllDrp0_25 %*
python trainNvidiaDrop.py --dataPath ./Record,./Recovery,./RecordOpposite,./Record1,./Record1Opposite --epochs 5 --offset 0.2 --output nvidAllDrp0_2 %*
python trainNvidiaDrop.py --dataPath ./Record,./Recovery,./RecordOpposite,./Record1,./Record1Opposite --epochs 5 --offset 0.15 --output nvidAllDrp0_15 %*
python trainNvidiaDrop.py --dataPath ./Record,./Recovery,./RecordOpposite,./Record1,./Record1Opposite --epochs 5 --offset 0.1 --output nvidAllDrp0_1 %*